name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]   

env:
  app_name: build_number${{ github.run_number }} 

jobs:
  build: 
    runs-on: windows-2022

    steps:
      - uses: actions/checkout@v3
      - name: Building application
        run: g++ hello.cpp -o ${{ runner.os }}-${{ env.app_name }}

      - name: Uploading result
        uses: actions/upload-artifact@v3
        with: 
          name: artifacts
          path: ${{ runner.os }}-${{ env.app_name }}

  message_sending: 
    needs: build
    
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - uses: actions/download-artifact@v3
        with:
          name: artifacts
          path: artifacts_folder
      
      - name: Telegram-bot
        uses: appleboy/telegram-action@master
        with: 
          to: ${{ secrets.CHAT_ID }}
          token: ${{ secrets.BOT_TOKEN }}
          message: 
            An event occured in ${{ github.repository }} repository
            ${{ github.event_name }}
          document: artifacts_folder/**
